default:
  extensions:
  - permit-pty
  - permit-X11-forwarding
  - permit-agent-forwarding
  - permit-port-forwarding
  - permit-user-rc
  valid_for: 1d
users:
  bob_wilson:
    extensions:
    - permit-port-forwarding
    - permit-X11-forwarding
    principals:
    - bob_wilson
    valid_for: 7d
  floppy: {}
  jane_smith:
    extensions:
    - permit-agent-forwarding
    principals:
    - jane_smith
    - admin
    - meep
    publickey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5...
    valid_for: 2
  john_doe:
    extensions:
    - permit-agent-forwarding
    - permit-port-forwarding
    password: gIuazvsABAj4u8bllnzq2o5FiwGJlpUDQbIqXbJmYxATQMMs0BeQZfMOzvLItB7rMbmQuIngOIfJA4Yx++lHO/BIaQ0yi41Ohi42h2B6ksk=
    principals:
    - john_doe
    - developer
    publickey: ssh-rsa AAAAB3NzaC1yc2E...
  meepmeep:
    # password: IT5Ss6nuESYFb3YGoeDtpir+oVBbyb0pr5iJPWt6LmYoMgmILEhlkzK0AC/gioRHnzgxhq9LoBjsRD/hS/u9dG0eILSA/JhVtrRF6AgKeCg=
    publickey: sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIH4nBbSR/F5ixbvGqIjqC0zFfF0mXxda4trABsjukqShAAAABHNzaDo= meepmeep@miramax
    valid_for: 10d
    principals:
      - meepmeep
      - pi
